version: '3'
services:
  pg:
    container_name: pg
    image: postgres
    restart: always
    ports:
      - "5355:5432"
    environment:
      POSTGRES_DB: website_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0192837465
  app:
    container_name: NewsWebsiteJavaApplication
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - pg
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/website_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0192837465

