CREATE TABLE Person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL,
                        lastname varchar(100) NOT NULL,
                        email varchar(100) NOT NULL,
                        password varchar(100) NOT NULL,
                        role varchar(15) DEFAULT 'ROLE_USER',
                        UNIQUE(email)
);

CREATE TABLE Post (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      text varchar(100) NOT NULL,
                      created_at timestamp,
                      pictures varchar(1000) NOT NULL,
                      UNIQUE(title)
);


CREATE TABLE Likes(
                      person_id int REFERENCES person(id) ON DELETE CASCADE,
                      post_id int REFERENCES post(id) ON DELETE CASCADE
);

CREATE TABLE Comments(
                         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         text varchar(1000),
                         person_id int REFERENCES person(id) ON DELETE CASCADE,
                         post_id int REFERENCES post(id) ON DELETE CASCADE,
                         created_at timestamp
);

CREATE TABLE Tags (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      text varchar(100) NOT NULL,
                      UNIQUE(text)
);


CREATE TABLE Themes(
                       tag_id int REFERENCES Tags(id) ON DELETE CASCADE,
                       post_id int REFERENCES post(id) ON DELETE CASCADE
);

CREATE TABLE Favor_Tags(
                           tag_id int REFERENCES Tags(id) ON DELETE CASCADE,
                           person_id int REFERENCES person(id) ON DELETE CASCADE
);

CREATE TABLE Banned(
                       tag_id int REFERENCES Tags(id) ON DELETE CASCADE,
                       person_id int REFERENCES person(id) ON DELETE CASCADE
);
